import { request } from './request';

export const getSchedulerDashboard = ({ start, end, type }: any) => {
  const typeSuffix = type ? `&type=${type}` : '';

  if (Math.random() > 0) {
    return {
      version: 748,
      myCalendar: [
        {
          cid: 'user_76793176417',
          name: 'baye',
          email: '',
          timeZone: '+8.00',
          timeZoneName: 'Asia/Shanghai',
          role: 'merger',
          events: [
            {
              cid: 'user_76793176417',
              eid: '6sp5a68mrn7pv2n4ctj4gek5qcb3bf14',
              topic: "Primo's Meeting",
              channelName: 'I-U2gyZ040UGF6SzNIdGhaeEFNVWRNQTRsVGxHak9CeEo=',
              start: 1768290840,
              end: 1768305240,
              host: '+72556268884',
              hostInfo: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'attendee',
              creator: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
          ],
        },
        {
          cid: 'user_72556268884',
          name: '',
          email: 'primo.l@chative.com',
          timeZone: '+8.00',
          timeZoneName: 'Asia/Shanghai',
          role: 'host',
          events: [
            {
              cid: 'user_72556268884',
              eid: '6sp5a68mrn7pv2n4ctj4gek5qcb3bf14',
              topic: "Primo's Meeting",
              channelName: 'I-U2gyZ040UGF6SzNIdGhaeEFNVWRNQTRsVGxHak9CeEo=',
              start: 1768290840,
              end: 1768305240,
              host: '+72556268884',
              hostInfo: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'host',
              creator: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_72556268884',
              eid: '1vh4l0qcl3pqb9pbbk14tmo93napl44a_20260113T100000Z',
              topic: "Primo's Meeting",
              channelName: 'I-Q0pxclZMQ2ZUSkhYdm83UXdYOGxCNFZUeHQ3WFZHMEg=',
              start: 1768298400,
              end: 1768305600,
              host: '+72556268884',
              hostInfo: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'host',
              creator: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              allDayStart: '20260113',
              allDayEnd: '20260114',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_72556268884',
              eid: '1vh4l0qcl3pqb9pbbk14tmo93napl44a_20260114T100000Z',
              topic: "Primo's Meeting",
              channelName: 'I-Q0pxclZMQ2ZUSkhYdm83UXdYOGxCNFZUeHQ3WFZHMEg=',
              start: 1768384800,
              end: 1768392000,
              host: '+72556268884',
              hostInfo: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'host',
              creator: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              allDayStart: '20260114',
              allDayEnd: '20260115',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_72556268884',
              eid: '1vh4l0qcl3pqb9pbbk14tmo93napl44a_20260115T100000Z',
              topic: "Primo's Meeting",
              channelName: 'I-Q0pxclZMQ2ZUSkhYdm83UXdYOGxCNFZUeHQ3WFZHMEg=',
              start: 1768471200,
              end: 1768478400,
              host: '+72556268884',
              hostInfo: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'host',
              creator: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              allDayStart: '20260115',
              allDayEnd: '20260116',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_72556268884',
              eid: '1vh4l0qcl3pqb9pbbk14tmo93napl44a_20260116T100000Z',
              topic: "Primo's Meeting",
              channelName: 'I-Q0pxclZMQ2ZUSkhYdm83UXdYOGxCNFZUeHQ3WFZHMEg=',
              start: 1768557600,
              end: 1768564800,
              host: '+72556268884',
              hostInfo: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'host',
              creator: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              allDayStart: '20260116',
              allDayEnd: '20260117',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_72556268884',
              eid: '1vh4l0qcl3pqb9pbbk14tmo93napl44a_20260117T100000Z',
              topic: "Primo's Meeting",
              channelName: 'I-Q0pxclZMQ2ZUSkhYdm83UXdYOGxCNFZUeHQ3WFZHMEg=',
              start: 1768644000,
              end: 1768651200,
              host: '+72556268884',
              hostInfo: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'host',
              creator: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              allDayStart: '20260117',
              allDayEnd: '20260118',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_72556268884',
              eid: '1vh4l0qcl3pqb9pbbk14tmo93napl44a_20260118T100000Z',
              topic: "Primo's Meeting",
              channelName: 'I-Q0pxclZMQ2ZUSkhYdm83UXdYOGxCNFZUeHQ3WFZHMEg=',
              start: 1768730400,
              end: 1768737600,
              host: '+72556268884',
              hostInfo: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'host',
              creator: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              allDayStart: '20260118',
              allDayEnd: '20260119',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_72556268884',
              eid: '1vh4l0qcl3pqb9pbbk14tmo93napl44a_20260119T100000Z',
              topic: "Primo's Meeting",
              channelName: 'I-Q0pxclZMQ2ZUSkhYdm83UXdYOGxCNFZUeHQ3WFZHMEg=',
              start: 1768816800,
              end: 1768824000,
              host: '+72556268884',
              hostInfo: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'host',
              creator: {
                uid: '+72556268884',
                name: 'Primo(DDDDDDDDDDDDDDDDDDDDDDD)',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              allDayStart: '20260119',
              allDayEnd: '20260120',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
          ],
        },
      ],
      otherCalendar: [
        {
          cid: 'user_78187805313',
          name: 'niko',
          email: 'niko@difft.org',
          timeZone: '+8.00',
          timeZoneName: 'Asia/Shanghai',
          role: '',
          events: [
            {
              cid: 'user_78187805313',
              eid: 'e807ejn9bl4jk7n5g1qtl76mfbcr7i8n_20260109T160000Z',
              topic: 'Busy',
              channelName: '',
              start: 1767974400,
              end: 1768233599,
              host: '+78187805313',
              hostInfo: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: 'host',
              creator: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'event',
              isAllDay: true,
              allDayStart: '20260109',
              allDayEnd: '20260113',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'e807ejn9bl4jk7n5g1qtl76mfbcr7i8n_20260110T160000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768060800,
              end: 1768319999,
              host: '+78187805313',
              hostInfo: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: 'host',
              creator: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'event',
              isAllDay: true,
              allDayStart: '20260110',
              allDayEnd: '20260114',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'e807ejn9bl4jk7n5g1qtl76mfbcr7i8n_20260111T160000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768147200,
              end: 1768406399,
              host: '+78187805313',
              hostInfo: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: 'host',
              creator: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'event',
              isAllDay: true,
              allDayStart: '20260111',
              allDayEnd: '20260115',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_71ojgcjm6gq6upb1ehj38sb5d9p6sdhiepp70t3hcgsjishne9gg_20260112T043200Z',
              topic: 'Busy',
              channelName: '',
              start: 1768192320,
              end: 1768194120,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=Xzcxb2pnY2ptNmdxNnVwYjFlaGozOHNiNWQ5cDZzZGhpZXBwNzB0M2hjZ3NqaXNobmU5Z2dfMjAyNjAxMTJUMDQzMjAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_64qmkpbfd4s6se37dosj0or8c9h76e3761j6aorg69i6esj6ctmg_20260112T044500Z',
              topic: 'Busy',
              channelName: '',
              start: 1768193100,
              end: 1768194900,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=XzY0cW1rcGJmZDRzNnNlMzdkb3NqMG9yOGM5aDc2ZTM3NjFqNmFvcmc2OWk2ZXNqNmN0bWdfMjAyNjAxMTJUMDQ0NTAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google8gkf4vh616u725q5r2e4klqp2vot078n_20260112T145000Z',
              topic: 'Busy',
              channelName: 'G-ZWJmNGU4NTFkNjIzNDAxMGJmOTU0OGM5NmZiZWQwZjA=',
              start: 1768229400,
              end: 1768231200,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=OGdrZjR2aDYxNnU3MjVxNXIyZTRrbHFwMnZvdDA3OG5fMjAyNjAxMTJUMTQ1MDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: 'ccm',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_e0p64opie4s6acr4epj6mrbje1o6kpjaegomasr8edi34sb7dtjg_20260112T151000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768230600,
              end: 1768232400,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=X2UwcDY0b3BpZTRzNmFjcjRlcGo2bXJiamUxbzZrcGphZWdvbWFzcjhlZGkzNHNiN2R0amdfMjAyNjAxMTJUMTUxMDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'e807ejn9bl4jk7n5g1qtl76mfbcr7i8n_20260112T160000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768233600,
              end: 1768492799,
              host: '+78187805313',
              hostInfo: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: 'host',
              creator: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'event',
              isAllDay: true,
              allDayStart: '20260112',
              allDayEnd: '20260116',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_71ojgcjm6gq6upb1ehj38sb5d9p6sdhiepp70t3hcgsjishne9gg_20260113T043200Z',
              topic: 'Busy',
              channelName: '',
              start: 1768278720,
              end: 1768280520,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=Xzcxb2pnY2ptNmdxNnVwYjFlaGozOHNiNWQ5cDZzZGhpZXBwNzB0M2hjZ3NqaXNobmU5Z2dfMjAyNjAxMTNUMDQzMjAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_64qmkpbfd4s6se37dosj0or8c9h76e3761j6aorg69i6esj6ctmg_20260113T044500Z',
              topic: 'Busy',
              channelName: '',
              start: 1768279500,
              end: 1768281300,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=XzY0cW1rcGJmZDRzNnNlMzdkb3NqMG9yOGM5aDc2ZTM3NjFqNmFvcmc2OWk2ZXNqNmN0bWdfMjAyNjAxMTNUMDQ0NTAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google8gkf4vh616u725q5r2e4klqp2vot078n_20260113T145000Z',
              topic: 'Busy',
              channelName: 'G-ZWJmNGU4NTFkNjIzNDAxMGJmOTU0OGM5NmZiZWQwZjA=',
              start: 1768315800,
              end: 1768317600,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=OGdrZjR2aDYxNnU3MjVxNXIyZTRrbHFwMnZvdDA3OG5fMjAyNjAxMTNUMTQ1MDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: 'ccm',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'googlev3tsl9vvhv040cup6p9u953hf8cij5rg',
              topic: 'Busy',
              channelName: 'I-VnNTalZRc3UxUWsxcVR4QnN2Z2t5cEdnSHIxQ1I4YzI=',
              start: 1768316400,
              end: 1768318200,
              host: '+75927296953',
              hostInfo: {
                uid: '+75927296953',
                name: 'Allen',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=djN0c2w5dnZodjA0MGN1cDZwOXU5NTNoZjhjaWo1cmcgbmlrb0BkaWZmdC5vcmc',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_e0p64opie4s6acr4epj6mrbje1o6kpjaegomasr8edi34sb7dtjg_20260113T151000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768317000,
              end: 1768318800,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=X2UwcDY0b3BpZTRzNmFjcjRlcGo2bXJiamUxbzZrcGphZWdvbWFzcjhlZGkzNHNiN2R0amdfMjAyNjAxMTNUMTUxMDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'e807ejn9bl4jk7n5g1qtl76mfbcr7i8n_20260113T160000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768320000,
              end: 1768579199,
              host: '+78187805313',
              hostInfo: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: 'host',
              creator: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'event',
              isAllDay: true,
              allDayStart: '20260113',
              allDayEnd: '20260117',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_71ojgcjm6gq6upb1ehj38sb5d9p6sdhiepp70t3hcgsjishne9gg_20260114T043200Z',
              topic: 'Busy',
              channelName: '',
              start: 1768365120,
              end: 1768366920,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=Xzcxb2pnY2ptNmdxNnVwYjFlaGozOHNiNWQ5cDZzZGhpZXBwNzB0M2hjZ3NqaXNobmU5Z2dfMjAyNjAxMTRUMDQzMjAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_64qmkpbfd4s6se37dosj0or8c9h76e3761j6aorg69i6esj6ctmg_20260114T044500Z',
              topic: 'Busy',
              channelName: '',
              start: 1768365900,
              end: 1768367700,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=XzY0cW1rcGJmZDRzNnNlMzdkb3NqMG9yOGM5aDc2ZTM3NjFqNmFvcmc2OWk2ZXNqNmN0bWdfMjAyNjAxMTRUMDQ0NTAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: '4vvu384e2h8p7f2jrgnn2mhuktcjj5mv_20260114T061000Z',
              topic: 'Busy',
              channelName: 'I-aW5KYVRmNjgxcFBFa0R5TGJGN2dmMFBlODQxbXR2OGw=',
              start: 1768371000,
              end: 1768372800,
              host: '+78187805313',
              hostInfo: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'host',
              creator: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              allDayStart: '20260114',
              allDayEnd: '20260115',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google8gkf4vh616u725q5r2e4klqp2vot078n_20260114T145000Z',
              topic: 'Busy',
              channelName: 'G-ZWJmNGU4NTFkNjIzNDAxMGJmOTU0OGM5NmZiZWQwZjA=',
              start: 1768402200,
              end: 1768404000,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=OGdrZjR2aDYxNnU3MjVxNXIyZTRrbHFwMnZvdDA3OG5fMjAyNjAxMTRUMTQ1MDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: 'ccm',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_e0p64opie4s6acr4epj6mrbje1o6kpjaegomasr8edi34sb7dtjg_20260114T151000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768403400,
              end: 1768405200,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=X2UwcDY0b3BpZTRzNmFjcjRlcGo2bXJiamUxbzZrcGphZWdvbWFzcjhlZGkzNHNiN2R0amdfMjAyNjAxMTRUMTUxMDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'e807ejn9bl4jk7n5g1qtl76mfbcr7i8n_20260114T160000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768406400,
              end: 1768665599,
              host: '+78187805313',
              hostInfo: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: 'host',
              creator: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'event',
              isAllDay: true,
              allDayStart: '20260114',
              allDayEnd: '20260118',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_71ojgcjm6gq6upb1ehj38sb5d9p6sdhiepp70t3hcgsjishne9gg_20260115T043200Z',
              topic: 'Busy',
              channelName: '',
              start: 1768451520,
              end: 1768453320,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=Xzcxb2pnY2ptNmdxNnVwYjFlaGozOHNiNWQ5cDZzZGhpZXBwNzB0M2hjZ3NqaXNobmU5Z2dfMjAyNjAxMTVUMDQzMjAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_64qmkpbfd4s6se37dosj0or8c9h76e3761j6aorg69i6esj6ctmg_20260115T044500Z',
              topic: 'Busy',
              channelName: '',
              start: 1768452300,
              end: 1768454100,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=XzY0cW1rcGJmZDRzNnNlMzdkb3NqMG9yOGM5aDc2ZTM3NjFqNmFvcmc2OWk2ZXNqNmN0bWdfMjAyNjAxMTVUMDQ0NTAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google8gkf4vh616u725q5r2e4klqp2vot078n_20260115T145000Z',
              topic: 'Busy',
              channelName: 'G-ZWJmNGU4NTFkNjIzNDAxMGJmOTU0OGM5NmZiZWQwZjA=',
              start: 1768488600,
              end: 1768490400,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=OGdrZjR2aDYxNnU3MjVxNXIyZTRrbHFwMnZvdDA3OG5fMjAyNjAxMTVUMTQ1MDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: 'ccm',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_e0p64opie4s6acr4epj6mrbje1o6kpjaegomasr8edi34sb7dtjg_20260115T151000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768489800,
              end: 1768491600,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=X2UwcDY0b3BpZTRzNmFjcjRlcGo2bXJiamUxbzZrcGphZWdvbWFzcjhlZGkzNHNiN2R0amdfMjAyNjAxMTVUMTUxMDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'e807ejn9bl4jk7n5g1qtl76mfbcr7i8n_20260115T160000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768492800,
              end: 1768751999,
              host: '+78187805313',
              hostInfo: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: 'host',
              creator: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'event',
              isAllDay: true,
              allDayStart: '20260115',
              allDayEnd: '20260119',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_71ojgcjm6gq6upb1ehj38sb5d9p6sdhiepp70t3hcgsjishne9gg_20260116T043200Z',
              topic: 'Busy',
              channelName: '',
              start: 1768537920,
              end: 1768539720,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=Xzcxb2pnY2ptNmdxNnVwYjFlaGozOHNiNWQ5cDZzZGhpZXBwNzB0M2hjZ3NqaXNobmU5Z2dfMjAyNjAxMTZUMDQzMjAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_64qmkpbfd4s6se37dosj0or8c9h76e3761j6aorg69i6esj6ctmg_20260116T044500Z',
              topic: 'Busy',
              channelName: '',
              start: 1768538700,
              end: 1768540500,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=XzY0cW1rcGJmZDRzNnNlMzdkb3NqMG9yOGM5aDc2ZTM3NjFqNmFvcmc2OWk2ZXNqNmN0bWdfMjAyNjAxMTZUMDQ0NTAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google8gkf4vh616u725q5r2e4klqp2vot078n_20260116T145000Z',
              topic: 'Busy',
              channelName: 'G-ZWJmNGU4NTFkNjIzNDAxMGJmOTU0OGM5NmZiZWQwZjA=',
              start: 1768575000,
              end: 1768576800,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=OGdrZjR2aDYxNnU3MjVxNXIyZTRrbHFwMnZvdDA3OG5fMjAyNjAxMTZUMTQ1MDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: 'ccm',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_e0p64opie4s6acr4epj6mrbje1o6kpjaegomasr8edi34sb7dtjg_20260116T151000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768576200,
              end: 1768578000,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=X2UwcDY0b3BpZTRzNmFjcjRlcGo2bXJiamUxbzZrcGphZWdvbWFzcjhlZGkzNHNiN2R0amdfMjAyNjAxMTZUMTUxMDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'e807ejn9bl4jk7n5g1qtl76mfbcr7i8n_20260116T160000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768579200,
              end: 1768838399,
              host: '+78187805313',
              hostInfo: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: 'host',
              creator: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'event',
              isAllDay: true,
              allDayStart: '20260116',
              allDayEnd: '20260120',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_71ojgcjm6gq6upb1ehj38sb5d9p6sdhiepp70t3hcgsjishne9gg_20260117T043200Z',
              topic: 'Busy',
              channelName: '',
              start: 1768624320,
              end: 1768626120,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=Xzcxb2pnY2ptNmdxNnVwYjFlaGozOHNiNWQ5cDZzZGhpZXBwNzB0M2hjZ3NqaXNobmU5Z2dfMjAyNjAxMTdUMDQzMjAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_64qmkpbfd4s6se37dosj0or8c9h76e3761j6aorg69i6esj6ctmg_20260117T044500Z',
              topic: 'Busy',
              channelName: '',
              start: 1768625100,
              end: 1768626900,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=XzY0cW1rcGJmZDRzNnNlMzdkb3NqMG9yOGM5aDc2ZTM3NjFqNmFvcmc2OWk2ZXNqNmN0bWdfMjAyNjAxMTdUMDQ0NTAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'bbc8crr9jl7gs6m8j066p39ecdves28a_20260117T100000Z',
              topic: 'Busy',
              channelName: 'I-dmVScElyTVVOVmVyZ2xwZDlsYXFaRXl5RWNacGNDeGE=',
              start: 1768644000,
              end: 1768645800,
              host: '+78187805313',
              hostInfo: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              googleLink: '',
              type: 'difft',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'difft',
              isLiveStream: false,
              permissions: {
                buttonCopy: 'readwrite',
              },
              role: 'host',
              creator: {
                uid: '+78187805313',
                name: '',
                timeZone: '',
              },
              appType: 'weatest',
              category: 'meeting',
              isAllDay: false,
              allDayStart: '20260117',
              allDayEnd: '20260118',
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google8gkf4vh616u725q5r2e4klqp2vot078n_20260117T145000Z',
              topic: 'Busy',
              channelName: 'G-ZWJmNGU4NTFkNjIzNDAxMGJmOTU0OGM5NmZiZWQwZjA=',
              start: 1768661400,
              end: 1768663200,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=OGdrZjR2aDYxNnU3MjVxNXIyZTRrbHFwMnZvdDA3OG5fMjAyNjAxMTdUMTQ1MDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: 'ccm',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_e0p64opie4s6acr4epj6mrbje1o6kpjaegomasr8edi34sb7dtjg_20260117T151000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768662600,
              end: 1768664400,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=X2UwcDY0b3BpZTRzNmFjcjRlcGo2bXJiamUxbzZrcGphZWdvbWFzcjhlZGkzNHNiN2R0amdfMjAyNjAxMTdUMTUxMDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_71ojgcjm6gq6upb1ehj38sb5d9p6sdhiepp70t3hcgsjishne9gg_20260118T043200Z',
              topic: 'Busy',
              channelName: '',
              start: 1768710720,
              end: 1768712520,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=Xzcxb2pnY2ptNmdxNnVwYjFlaGozOHNiNWQ5cDZzZGhpZXBwNzB0M2hjZ3NqaXNobmU5Z2dfMjAyNjAxMThUMDQzMjAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_64qmkpbfd4s6se37dosj0or8c9h76e3761j6aorg69i6esj6ctmg_20260118T044500Z',
              topic: 'Busy',
              channelName: '',
              start: 1768711500,
              end: 1768713300,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=XzY0cW1rcGJmZDRzNnNlMzdkb3NqMG9yOGM5aDc2ZTM3NjFqNmFvcmc2OWk2ZXNqNmN0bWdfMjAyNjAxMThUMDQ0NTAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google8gkf4vh616u725q5r2e4klqp2vot078n_20260118T145000Z',
              topic: 'Busy',
              channelName: 'G-ZWJmNGU4NTFkNjIzNDAxMGJmOTU0OGM5NmZiZWQwZjA=',
              start: 1768747800,
              end: 1768749600,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=OGdrZjR2aDYxNnU3MjVxNXIyZTRrbHFwMnZvdDA3OG5fMjAyNjAxMThUMTQ1MDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: 'ccm',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_e0p64opie4s6acr4epj6mrbje1o6kpjaegomasr8edi34sb7dtjg_20260118T151000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768749000,
              end: 1768750800,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=X2UwcDY0b3BpZTRzNmFjcjRlcGo2bXJiamUxbzZrcGphZWdvbWFzcjhlZGkzNHNiN2R0amdfMjAyNjAxMThUMTUxMDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_71ojgcjm6gq6upb1ehj38sb5d9p6sdhiepp70t3hcgsjishne9gg_20260119T043200Z',
              topic: 'Busy',
              channelName: '',
              start: 1768797120,
              end: 1768798920,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=Xzcxb2pnY2ptNmdxNnVwYjFlaGozOHNiNWQ5cDZzZGhpZXBwNzB0M2hjZ3NqaXNobmU5Z2dfMjAyNjAxMTlUMDQzMjAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_64qmkpbfd4s6se37dosj0or8c9h76e3761j6aorg69i6esj6ctmg_20260119T044500Z',
              topic: 'Busy',
              channelName: '',
              start: 1768797900,
              end: 1768799700,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=XzY0cW1rcGJmZDRzNnNlMzdkb3NqMG9yOGM5aDc2ZTM3NjFqNmFvcmc2OWk2ZXNqNmN0bWdfMjAyNjAxMTlUMDQ0NTAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google8gkf4vh616u725q5r2e4klqp2vot078n_20260119T145000Z',
              topic: 'Busy',
              channelName: 'G-ZWJmNGU4NTFkNjIzNDAxMGJmOTU0OGM5NmZiZWQwZjA=',
              start: 1768834200,
              end: 1768836000,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=OGdrZjR2aDYxNnU3MjVxNXIyZTRrbHFwMnZvdDA3OG5fMjAyNjAxMTlUMTQ1MDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: 'ccm',
              category: 'meeting',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
            {
              cid: 'user_78187805313',
              eid: 'google_e0p64opie4s6acr4epj6mrbje1o6kpjaegomasr8edi34sb7dtjg_20260119T151000Z',
              topic: 'Busy',
              channelName: '',
              start: 1768835400,
              end: 1768837200,
              host: '48d3104b4aa1959f527468aa9d95d44f',
              hostInfo: {
                uid: '48d3104b4aa1959f527468aa9d95d44f',
                name: 'niko.y',
                timeZone: '',
              },
              googleLink:
                'https://www.google.com/calendar/event?eid=X2UwcDY0b3BpZTRzNmFjcjRlcGo2bXJiamUxbzZrcGphZWdvbWFzcjhlZGkzNHNiN2R0amdfMjAyNjAxMTlUMTUxMDAwWiBuaWtvQGRpZmZ0Lm9yZw',
              type: 'gg',
              going: 'maybe',
              receiveNotification: true,
              muted: false,
              source: 'google',
              isLiveStream: false,
              permissions: {
                buttonCopy: '-',
              },
              role: '',
              creator: null,
              appType: '',
              category: 'event',
              isAllDay: false,
              googleMeetingLink: '',
              outlookMeetingLink: '',
            },
          ],
        },
      ],
    };
  }

  return request.get(
    `v1/calendar/dashboard?start=${start}&end=${end}&t=${Date.now()}${typeSuffix}`
  ) as any;
};

export const addUserCalendar = async (data: { cid: string; type: string; name?: string }) => {
  return request.post(`v1/user/calendar`, { json: data }) as any;
};

export const deleteUserCalendar = async (data: { cid: string; type: string }) => {
  return request.delete(`v1/user/calendar`, { json: data }) as any;
};

export const updateUserCalendar = async (data: { cid: string; type: string; name?: string }) => {
  return request.put(`v1/user/calendar`, { json: data }) as any;
};

export const uploadIcsData = async (data: { ics: string; email?: string }) => {
  return request.post(`v1/ics/upload`, { json: data }) as any;
};

export const addLiveStreamToCalendar = async (eid: string, cid = 'default') => {
  return request.post(`v1/calendar/${cid}/livestream`, {
    json: { eid },
  });
};

export const deleteMeetingSchedule = async (data: any) => {
  const { calendarId = 'default', eventId, isAllEvent = false, isRecurring = false } = data;

  return request.delete(
    `v1/calendar/${encodeURIComponent(calendarId)}/events/${eventId}?isAllEvent=${isAllEvent}&isRecurring=${isRecurring}`
  ) as any;
};

export const goingScheduleMeeting = async (data: any) => {
  const { eventId, calendarId, going, isRecurring, isAllEvent } = data;

  return request.put(`v1/calendar/${calendarId}/events/${eventId}/going`, {
    json: { going, isRecurring, isAllEvent },
  }) as any;
};

export const scheduleMeetingReceiveNotify = async (data: any) => {
  const {
    calendarId = 'default',
    eventId,
    receiveNotification = false,
    isRecurring = false,
    isAllEvent = false,
  } = data;

  return request.put(
    `v1/calendar/${encodeURIComponent(calendarId)}/events/${eventId}/notification`,
    { json: { isRecurring, isAllEvent, receiveNotification } }
  ) as any;
};

export const copyScheduleMeetingInfo = async (data: any) => {
  const { calendarId = 'default', eventId, action = 'copy' } = data;
  return request.get(
    `v1/calendar/${encodeURIComponent(calendarId)}/events/${eventId}/copy?type=difft&action=${action}`
  ) as any;
};

export const getSchedulerCreateConfig = (calendarId: string) => {
  return request.post(`v1/calendar/${encodeURIComponent(calendarId)}/events/precreate`, {
    json: {
      calendarId,
      features: ['canSyncGoogle'],
    },
  }) as any;
};

export const getSchedulerOrgInfo = () => {
  return request.get(`v1/org/users`) as any;
};

export const getMeetingViewScheduleList = async (data: any) => {
  const { users = [], start, end } = data;
  return request.post(`v1/user/freebusy`, {
    json: { users, start, end },
  }) as any;
};

export const scheduleMeetingGetFreeTime = async (data: any) => {
  const { uid, start, end } = data;

  return request.get(`v1/user/${uid}/freebusy?start=${start}&end=${end}`, {});
};

export const scheduleMeetingGetGroupFreeTime = async (data: any) => {
  const { gid, start, end } = data;

  return request.get(`v1/group/${gid}/freebusy?start=${start}&end=${end}`, {});
};

export const createMeetingSchedule = async (data: any) => {
  const { calendarId = 'default', ...body } = data;
  return request.post(`v1/calendar/${encodeURIComponent(calendarId)}/events`, {
    json: body,
    headers: {
      'x-full-response': '1',
    },
  }) as any;
};

export const updateMeetingSchedule = async (data: any) => {
  const { calendarId = 'default', eventId, ...body } = data;
  return request.put(`v1/calendar/${encodeURIComponent(calendarId)}/events/${eventId}`, {
    json: body,
    headers: {
      'x-full-response': '1',
    },
  }) as any;
};

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const onMuteMeeting = async (item: any) => {
  return { data: item, success: true, reason: null };
};

export const getMeetingScheduleDetail = async (options: any) => {
  await delay(1000);
  console.log('Mocked getMeetingScheduleDetail called', options);
  return {
    event: {
      eid: 'oGqlDtpykVMCkmCWFMUIWcKQKCBUMHgq_20260116T023000Z',
      topic: 'Desktop & Web Weekly Report',
      description: '',
      channelName: 'G-NDc5NGNmODFhZGIwNDY0Zjk0OTVhNWM3YWVkNjJhMmM=',
      host: '+77067007821',
      hostInfo: {
        uid: '+77067007821',
        name: 'Jason(cc)',
        timeZone: '',
      },
      start: 1768530600,
      end: 1768532400,
      isAllDay: false,
      isRecurring: true,
      recurringRule: {
        rrule: 'FREQ=WEEKLY;INTERVAL=1',
        dtStart: 0,
        dtEnd: 0,
        repeat: 'Weekly',
        repeatOptions: [
          {
            label: 'Never',
            value: 'Never',
          },
          {
            label: 'Daily',
            value: 'FREQ=DAILY;INTERVAL=1',
          },
          {
            label: 'Weekdays',
            value: 'FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR',
          },
          {
            label: 'Weekly',
            value: 'FREQ=WEEKLY;INTERVAL=1',
          },
          {
            label: 'Biweekly',
            value: 'FREQ=WEEKLY;INTERVAL=2',
          },
          {
            label: 'Monthly',
            value: 'FREQ=MONTHLY;INTERVAL=1',
          },
        ],
      },
      timezone: 'Asia/Shanghai',
      attendees: [
        {
          uid: '+77067007821',
          name: 'Jason(cc)',
          email: 'jason@chative.com',
          role: 'host',
          going: 'maybe',
          isGroupUser: true,
          isRemovable: false,
        },
        {
          uid: '+79331532255',
          name: 'Bruce (Tools)',
          email: 'bruce@chative.com',
          role: 'attendee',
          going: 'maybe',
          isGroupUser: true,
          isRemovable: false,
        },
        {
          uid: '+71920467649',
          name: 'Luke(TT)',
          email: 'luke@chative.com',
          role: 'attendee',
          going: 'maybe',
          isGroupUser: true,
          isRemovable: false,
        },
        {
          uid: '+77361741867',
          name: 'p1rimo(cc)',
          email: 'primo.l@chative.com',
          role: 'attendee',
          going: 'maybe',
          isGroupUser: true,
          isRemovable: false,
        },
        {
          uid: '+78131806055',
          name: 'Reeve(TT)',
          email: 'reeve.c@chative.com',
          role: 'attendee',
          going: 'maybe',
          isGroupUser: true,
          isRemovable: false,
        },
        {
          uid: '+76722386418',
          name: 'Thomas(cc)',
          email: 'thomas@chative.com',
          role: 'attendee',
          going: 'yes',
          isGroupUser: true,
          isRemovable: false,
        },
        {
          uid: '+72991507254',
          name: 'Tristan(cc)',
          email: 'tristan.q@chative.com',
          role: 'attendee',
          going: 'maybe',
          isGroupUser: true,
          isRemovable: false,
        },
        {
          uid: '+74584819829',
          name: 'Kami (cc)',
          email: 'kami.c@chative.com',
          role: 'attendee',
          going: 'maybe',
          isGroupUser: true,
          isRemovable: false,
        },
        {
          uid: '+73633550045',
          name: 'Kayne  (cc)',
          email: 'kayne@chative.com',
          role: 'attendee',
          going: 'maybe',
          isGroupUser: true,
          isRemovable: false,
        },
        {
          uid: '+75750780825',
          name: 'Shawn(cc)',
          email: 'shiyun.h@chative.com',
          role: 'attendee',
          going: 'maybe',
          isGroupUser: true,
          isRemovable: false,
        },
        {
          uid: '+79757594493',
          name: 'Will(cc)',
          email: 'will.g@chative.com',
          role: 'attendee',
          going: 'maybe',
          isGroupUser: true,
          isRemovable: false,
        },
      ],
      isGroup: true,
      group: {
        gid: '4794cf81adb0464f9495a5c7aed62a2c',
        name: 'Desktop & Web 开发组',
      },
      attachment: [
        {
          name: 'Desktop & Web Weekly Report',
          link: 'https://docman.doclite.org/officeman/?action=read&fileId=b0aa0be0-b2e4-4356-b306-1124f6a052f9&tk=ab956f18-431b-49ed-be54-30b8e4c3da39#detail/',
        },
      ],
      everyoneCanInviteOthers: true,
      everyoneCanModify: false,
      type: 'difft',
      source: 'difft',
      isLiveStream: false,
      guests: {
        allStaff: false,
        orgId: '',
        users: [],
        total: 0,
      },
      creator: {
        uid: '+77067007821',
        name: '',
        timeZone: '',
      },
      appType: 'ccm',
      category: '',
      syncToGoogle: false,
      googleMeetingLink: '',
      outlookMeetingLink: '',
      speechTimerEnabled: false,
      speechTimer: null,
    },
    canInvite: true,
    canModify: false,
    going: 'maybe',
    cid: 'user_77361741867',
    timeZone: 'Asia/Shanghai',
    receiveNotification: true,
    permissions: {
      editMode: {
        buttonUpdate: 'readwrite',
        buttonEdit: '-',
        buttonDelete: '-',
        textFieldTitle: 'read',
        pickerStartDateTime: 'read',
        selectorDuration: 'read',
        selectorRepeat: 'read',
        selectorAttendee: 'readwrite',
        textHost: 'read',
        editorAttachment: 'read',
        textFieldDesc: 'read',
        checkboxEveryoneCanModifyMeeting: '-',
        checkboxEveryoneCanInviteOthers: '-',
        checkboxSendInvitationToTheChatRoom: '-',
        toggleGoingOrNot: '-',
        checkboxReceiveNotification: '-',
        buttonCopy: '-',
        buttonFindATime: 'readwrite',
        buttonAddLiveStream: '-',
        buttonCopyLiveStream: '-',
        buttonJoin: '-',
        buttonTransferHost: '-',
        buttonDuplicate: '-',
        checkboxIsAllDay: '-',
        pickerEndDateTime: '-',
      },
      viewMode: {
        buttonUpdate: '-',
        buttonEdit: 'readwrite',
        buttonDelete: 'readwrite',
        textFieldTitle: 'read',
        pickerStartDateTime: 'read',
        selectorDuration: 'read',
        selectorRepeat: 'read',
        selectorAttendee: 'read',
        textHost: 'read',
        editorAttachment: 'read',
        textFieldDesc: 'read',
        checkboxEveryoneCanModifyMeeting: '-',
        checkboxEveryoneCanInviteOthers: '-',
        checkboxSendInvitationToTheChatRoom: '-',
        toggleGoingOrNot: 'readwrite',
        checkboxReceiveNotification: 'readwrite',
        buttonCopy: 'readwrite',
        buttonFindATime: '-',
        buttonAddLiveStream: '-',
        buttonCopyLiveStream: '-',
        buttonJoin: '-',
        buttonTransferHost: '-',
        buttonDuplicate: 'readwrite',
        checkboxIsAllDay: '-',
        pickerEndDateTime: '-',
      },
    },
  };
};
